# https://starship.rs/config/

format = """
$username\
$hostname\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$hg_branch\
$docker_context\
$deno\
$nodejs\
$python\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

scan_timeout = 10

add_newline = false

palette = 'foo'

[palettes.foo]
blue = '21'
mustard = '#af8700'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[git_branch]
